name: The Thought full Leader
favicon: null
layout_spectrum: 0.6957038559485227
typography_spectrum: 0.6169542178977281
title: The Thought full Leader
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6801666032988578
  lightness: 0.4639443645719439
  saturation: 0.08810217818245292
  rhythmicContrast: 0.372118596220389
purpose: []
